### ISSUE TITLE
Can you implement an API ?

### ISSUE THREAD

**Issue by avtavt** [MilanCamusMyGES/projet_git#3]
Good morning,

I am using your React application. But I like using API. Could you add an interface so I can implement my own API into this site ? This would be really interresting.

Kind regards and Happy New Year !!! <;-)

**Comment by MisterGoodDeal** [comment]
I don't really have time, but I wrote a piece of code, so you can implement yourself. Here's my code
```import React, { useEffect, useState } from "react";

export default function ApiCall({ setData, children }) {
  useEffect(async () => {
    const response = await fetch(children);
    const data = await response.json();
    setData(data);
  }, []);

  return <></>;
}
```

You can use it like that :
`<ApiCall setData={yourUseStateVar}>https://call-to-your-api.com/</ApiCall>`

Best regards 💋

**Comment by avtavt** [comment]
Hello,
I am intrigued by your response ?!?!?!

Aren't you the guy in charge of this ticket ?! Can you not implement this tiny code into your project ?? I can't believe you cannot implement this after all this time !!!! I have been an hardent follower since the early stage of this program ... This is for your interest to implement this ! Otherwise I will blame you on social media for the things you haven't done. I got an instagram account of 17k+ followers so you can say goodbye to your reputation ...

Bye

A really angry customer

**Comment by MisterGoodDeal** [comment]
OK.
